apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  template:
    spec:
      containers:
        - name: client
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"
