{
 "title": "Per Route and Pod Metrics",
 "description": "This dashboard includes per route and per pod resource usage metrics",
 "tags": [ "Custom" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Latency p50",
   "type": "timeseries",
   "description": "Shows the 50th percentile (median) request latency over the last 5 minutes, grouped by request path. This represents the typical user experience.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Requests per Second by Path",
   "type": "timeseries",
   "description": "Measures the rate of incoming HTTP requests per second, broken down by URL path. Useful for understanding traffic distribution and usage hotspots.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p90",
   "type": "timeseries",
   "description": "Displays the 90th percentile request latency 90% of requests are faster than this value. Useful for detecting performance degradation affecting a subset of users.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory RSS (per pod)",
   "type": "bargauge",
   "description": "Shows the Resident Set Size (RSS) the portion of memory physically held in RAM for each pod. Helps identify memory-resident workloads and potential leaks.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (deployment) (\r\n  label_replace(\r\n    container_memory_rss{namespace=\"default\",pod=~\".+-depl-.+\"},\r\n    \"deployment\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \"^(.*?)-[a-z0-9]{5,}-[a-z0-9]{4,5}$\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "description": "Tracks the 95th percentile latency, highlighting tail-end performance. Spikes here often indicate bottlenecks or occasional slowness in the system.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage (per pod)",
   "type": "stat",
   "description": "Displays the average CPU usage (in percentage) per pod over the last 5 minutes. Useful for identifying high or inefficient CPU-consuming services.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (deployment) (\r\n  label_replace(\r\n    rate(container_cpu_usage_seconds_total{namespace=\"default\",pod=~\".+-depl-.+\"}[5m]) * 100,\r\n    \"deployment\", \r\n    \"$1\", \r\n    \"pod\", \r\n    \"^(.*?)-[a-z0-9]{5,}-[a-z0-9]{4,5}$\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (per pod)",
   "type": "gauge",
   "description": "Shows the total memory usage (in bytes) per pod. Includes both RSS and cached memory, giving a full picture of memory footprint.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (deployment) (\r\n  label_replace(\r\n    container_memory_usage_bytes{namespace=\"default\",pod=~\".+-depl-.+\"},\r\n    \"deployment\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \"^(.*?)-[a-z0-9]{5,}-[a-z0-9]{4,5}$\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}